name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # NOTE: UTCなので9時間引く
    # 毎週土曜日の22時に実行
    - cron: 0 11 * * 6
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 20.8.1
        cache: yarn

    - name: Install dependencies
      run: yarn install

    - name: Run type check
      run: yarn type-check

    - name: Lint
      run: yarn lint

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 20.8.1
        cache: yarn

    - name: Install dependencies
      run: yarn install

    - name: Test
      run: yarn test

  generate:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 20.8.1
        cache: yarn

    - name: Install dependencies
      run: yarn install

    - name: Generate feed
      run: yarn feed-generate

    - name: Generate site
      run: yarn site-build
