name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # NOTE: UTCなので9時間引く
    # 毎週土曜日の午前9時に実行
    - cron: 0 0 * * 6
  workflow_dispatch:

jobs:
  lint-biome:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: yarn
    - run: yarn install
    - run: yarn lint-biome && git diff --exit-code

  lint-ts:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: yarn
    - run: yarn install
    - run: yarn lint-ts

  lint-secretlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: yarn
    - run: yarn install
    - run: yarn lint-secretlint

  validate-renovate-config:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
    - name: Validate Renovate config
      run: npx --yes --package renovate -- renovate-config-validator --strict

  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: yarn
    - run: yarn install
    - run: yarn test-coverage

  generate:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: yarn
    - run: yarn install
    - name: Generate feed
      run: yarn feed-generate
    - name: Generate site
      run: yarn site-build
    - name: Archive feed
      uses: actions/upload-artifact@v4
      with:
        name: feed-generate-results
        path: public/feeds
